/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        darkBg: "#0d1117",
        darkCard: "rgba(30, 41, 59, 0.7)",
        surface: "#131313",
        surfaceElevated: "#1c2333",
        borderDefault: "#21262d",
        borderMuted: "#30363d",
        primary: "#ffb693",
        accent: "#22c55e",
        accentHover: "#16a34a",
        fire: "#f59e0b",
        muted: "#8b949e",
        mutedDim: "#6e7681",
        mutedFaint: "#484f58",
        "primary-fixed": "#ffdbcc",
        "neon-accent": "#FF8A3D",
        "tertiary-fixed-dim": "#9ccaff",
        "on-tertiary-fixed-variant": "#00497b",
        "surface-dim": "#131313",
        "error": "#ffb4ab",
        "outline": "#a98a7d",
        "surface-tint": "#ffb693",
        "error-container": "#93000a",
        "on-tertiary-container": "#003357",
        "surface-container-highest": "#353534",
        "primary-fixed-dim": "#ffb693",
        "surface-container-lowest": "#0e0e0e",
        "on-secondary-fixed-variant": "#2e3aa2",
        "secondary-container": "#2e3aa2",
        "tertiary-fixed": "#d0e4ff",
        "outline-variant": "#5a4136",
        "surface-container": "#201f1f",
        "on-surface-variant": "#e2bfb0",
        "inverse-on-surface": "#313030",
        "surface-container-low": "#1c1b1b",
        "on-error-container": "#ffdad6",
        "on-background": "#e5e2e1",
        "secondary": "#bdc2ff",
        "background": "#131313",
        "on-secondary": "#121f8b",
        "on-error": "#690005",
        "surface-container-high": "#2a2a2a",
        "inverse-surface": "#e5e2e1",
        "primary-container": "#ff6b00",
        "on-tertiary-fixed": "#001d35",
        "on-secondary-fixed": "#000965",
        "on-primary-fixed": "#351000",
        "on-primary": "#561f00",
        "on-primary-fixed-variant": "#7a3000",
        "secondary-fixed": "#dfe0ff",
        "on-primary-container": "#572000",
        "inverse-primary": "#a04100",
        "terminal-yellow": "#E4F222",
        "surface-bright": "#3a3939",
        "surface-variant": "#353534",
        "tertiary": "#9ccaff",
        "secondary-fixed-dim": "#bdc2ff",
        "surface-stroke": "rgba(255, 255, 255, 0.1)",
        "on-tertiary": "#003257",
        "tertiary-container": "#059eff",
        "on-surface": "#e5e2e1",
        "on-secondary-container": "#a7afff",
        "aurora-glow": "rgba(255, 107, 0, 0.15)"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
        "premium": "28px"
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
        "body-md": ["Inter"],
        "body-lg": ["Inter"],
        "body-sm": ["Inter"],
        "mono-label": ["JetBrains Mono", "monospace"],
        "mono-code": ["JetBrains Mono", "monospace"],
        "headline-xl": ["Outfit", "sans-serif"],
        "headline-lg": ["Outfit", "sans-serif"],
        "headline-md": ["Outfit", "sans-serif"],
        "headline-lg-mobile": ["Outfit", "sans-serif"],
      },
      fontSize: {
        "body-md": ["16px", { "lineHeight": "24px", "letterSpacing": "0em", "fontWeight": "400" }],
        "headline-lg-mobile": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "28px", "letterSpacing": "0em", "fontWeight": "400" }],
        "label-caps": ["12px", { "lineHeight": "16px", "letterSpacing": "0.1em", "fontWeight": "600" }],
        "display": ["72px", { "lineHeight": "80px", "letterSpacing": "-0.04em", "fontWeight": "700" }],
        "headline-md": ["24px", { "lineHeight": "32px", "letterSpacing": "0em", "fontWeight": "600" }],
        "headline-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "code-snippet": ["14px", { "lineHeight": "20px", "fontWeight": "400" }]
      },
      spacing: {
        'sidebar': '240px',
        'navbar': '56px',
        "section-padding": "120px",
        "gutter": "24px",
        "container-max": "1200px",
        "margin-mobile": "20px",
        "base": "8px"
      },
      animation: {
        'fadeSlideUp': 'fadeSlideUp 0.4s cubic-bezier(0.4, 0, 0.2, 1) forwards',
        'scaleIn': 'scaleIn 0.25s cubic-bezier(0.4, 0, 0.2, 1) forwards',
        'pulseGlow': 'pulseGlow 2.5s ease-in-out infinite',
      },
      keyframes: {
        fadeSlideUp: {
          '0%': { opacity: '0', transform: 'translateY(16px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        scaleIn: {
          '0%': { opacity: '0', transform: 'scale(0.95)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        pulseGlow: {
          '0%, 100%': { boxShadow: '0 0 0 0 rgba(34, 197, 94, 0.3)' },
          '50%': { boxShadow: '0 0 16px 4px rgba(34, 197, 94, 0.15)' },
        },
      },
    },
  },
  plugins: [],
}

